version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
